### ISSUE TITLE
Dont load

### ISSUE THREAD

**Issue by Finlay00** [stevin05/CraftScan#3] opened 2024-07-31 14:58 UTC
Bugsack Error addon dont run

Error 19926
15x CraftScan/Utils/Utils.lua:300: table index is nil
[string "@CraftScan/Utils/Utils.lua"]:300: in function <CraftScan/Utils/Utils.lua:295>
[string "@CraftScan/RecipeSchematicMenu.lua"]:530: in function <CraftScan/RecipeSchematicMenu.lua:500>
[string "=[C]"]: in function `SelectRecipe'
[string "@Blizzard_Professions/Blizzard_ProfessionsCrafting.lua"]:369: in function <...lizzard_Professions/Blizzard_ProfessionsCrafting.lua:360>
[string "=[C]"]: ?
[string "@Blizzard_SharedXMLBase/CallbackRegistry.lua"]:144: in function <...eBlizzard_SharedXMLBase/CallbackRegistry.lua:143>
[string "=[C]"]: ?
[string "@Blizzard_SharedXMLBase/CallbackRegistry.lua"]:147: in function `TriggerEvent'
[string "@Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeList.lua"]:137: in function <...fessionsTemplates/Blizzard_ProfessionsRecipeList.lua:124>
[string "=[C]"]: ?
[string "@Blizzard_SharedXMLBase/CallbackRegistry.lua"]:144: in function <...eBlizzard_SharedXMLBase/CallbackRegistry.lua:143>
[string "=[C]"]: ?
...
[string "@Blizzard_SharedXML/Shared/Scroll/ScrollUtil.lua"]:486: in function `SelectElementDataByPredicate'
[string "@Blizzard_ProfessionsTemplates/Blizzard_ProfessionsRecipeList.lua"]:159: in function `SelectRecipe'
[string "@Blizzard_Professions/Blizzard_ProfessionsCrafting.lua"]:886: in function `Init'
[string "@Blizzard_Professions/Blizzard_ProfessionsCrafting.lua"]:357: in function <...lizzard_Professions/Blizzard_ProfessionsCrafting.lua:356>
[string "=[C]"]: ?
[string "@Blizzard_SharedXMLBase/CallbackRegistry.lua"]:144: in function <...eBlizzard_SharedXMLBase/CallbackRegistry.lua:143>
[string "=[C]"]: ?
[string "@Blizzard_SharedXMLBase/CallbackRegistry.lua"]:147: in function `TriggerEvent'
[string "@Blizzard_Professions/Blizzard_ProfessionsFrame.lua"]:207: in function `SetProfessionInfo'
[string "@Blizzard_Professions/Blizzard_ProfessionsFrame.lua"]:139: in function <...s/Blizzard_Professions/Blizzard_ProfessionsFrame.lua:102>

Locals:
parent = <table> {
 755 = <table> {
 }
 773 = <table> {
 }
}
child = nil
default = <table> {
 sound_alert_enabled = false
 visual_alert_enabled = true
 scanning_enabled = true
}
(*temporary) = nil
(*temporary) = "table index is nil"

**Comment by stevin05** [comment] 2024-07-31 16:11
The code generating the error is when a recipe is selected in a profession window. I can fix it to not cause an error, but I need to understand why the parentProfessionID is not available in this case or the menus will not behave correctly.

1. Does this happen immediately when you log on? 
2. Did it happen when selecting a specific recipe?
3. What professions?
4. What recipe?


Der Code, der den Fehler erzeugt, tritt auf, wenn ein Rezept in einem Berufsfenster ausgewählt wird. Ich kann es so korrigieren, dass kein Fehler mehr auftritt, aber ich muss verstehen, warum in diesem Fall die parentProfessionID nicht verfügbar ist, sonst werden die Menüs nicht korrekt funktionieren.

    Tritt dies sofort beim Einloggen auf?
    Ist es passiert, als Sie ein bestimmtes Rezept ausgewählt haben?
    Welche Berufe?
    Welches Rezept?

**Comment by Finlay00** [comment] 2024-07-31 17:03
Since today the addon has started, no matter what job it is. Professions window just looks like the addon is off
Play in German

**Comment by stevin05** [comment] 2024-07-31 20:41
v1.0.6 adds a debug print to help me see what the problem is. Please copy/paste it here once you update and hit the problem again.

Instead of crashing, a window should pop up with a table printed in it.

**Comment by Finlay00** [comment] 2024-08-01 03:07
1x CraftScan/Utils/Utils.lua:305: table index is nil
[string "@CraftScan/Utils/Utils.lua"]:305: in function `saved'
[string "@CraftScan/Utils/Utils.lua"]:380: in function <CraftScan/Utils/Utils.lua:364>
[string "@CraftScan/Utils/Utils.lua"]:552: in function <CraftScan/Utils/Utils.lua:522>
[string "@CraftScan/Utils/Utils.lua"]:618: in function <CraftScan/Utils/Utils.lua:616>

Locals:
parent = <table> {
 755 = <table> {
 }
 773 = <table> {
 }
}
child = nil
default = <table> {
 sound_alert_enabled = false
 visual_alert_enabled = true
 scanning_enabled = true
}
(*temporary) = nil
(*temporary) = "table index is nil"

![Screenshot_67](https://github.com/user-attachments/assets/ff90a1ca-502e-403d-a215-9aa533a3c75d)

only bugsack and buggrabber addon is aktiv and craftscan

**Comment by stevin05** [comment] 2024-08-01 13:46
Should be fixed in 1.0.7.

That backtrace makes more sense. Was able to reproduce and fix. You had cooking or fishing data in your WTF from before I started filtering them out. The new version should automatically erase any secondary professions that made it into the config files.

**Comment by Finlay00** [comment] 2024-08-01 16:04
3x CraftScan/Utils/Utils.lua:306: table index is nil
[string "@CraftScan/Utils/Utils.lua"]:306: in function `saved'
[string "@CraftScan/Utils/Utils.lua"]:385: in function <CraftScan/Utils/Utils.lua:365>
[string "@CraftScan/Utils/Utils.lua"]:562: in function <CraftScan/Utils/Utils.lua:532>
[string "@CraftScan/Utils/Utils.lua"]:628: in function <CraftScan/Utils/Utils.lua:626>

Locals:
parent = <table> {
 755 = <table> {
 }
 773 = <table> {
 }
}
child = nil
default = <table> {
 sound_alert_enabled = false
 visual_alert_enabled = true
 scanning_enabled = true
}
(*temporary) = nil
(*temporary) = "table index is nil"

OK, if I empty the WTF folder... craftscan runs as soon as I put my WTF data back in, it doesn't work anymore... and now I get the error according to bugsack

**Comment by Finlay00** [comment] 2024-08-01 18:06
okey i delete the addon saved variables and now it works

**Comment by stevin05** [comment] 2024-08-01 18:38
Can you attach the bad CraftScan.lua from your WTF here? Would like to figure out what's still broken so no one else gets blocked.

**Comment by Finlay00** [comment] 2024-08-01 19:15
[craftscan Lua.txt](https://github.com/user-attachments/files/16460956/craftscan.Lua.txt)
[craftscan.lua.bak.txt](https://github.com/user-attachments/files/16460967/craftscan.lua.bak.txt)

sry had to copy it into a text file and I couldn't load the lua file

**Comment by stevin05** [comment] 2024-08-02 13:28
Thanks. Somehow this got in there. I guess this is that 'profession' in the emerald dream for turning in boxes. For some reason it is flagged as 'isPrimaryProfession = true'.

`
[2886] = { },
`

`profInfo: {
  skillLevel = 0
  professionID = 2886
  sourceCounter = 0
  isPrimaryProfession = true
  skillModifier = 0
  professionName = Supply Shipments
  maxSkillLevel = 0
  expansionName = Unknown
}`

**Comment by Finlay00** [comment] 2024-08-02 13:42
Okay, then it's good that you found very few things that were wrong! I think your addon is very good because it does exactly that... but I don't feel like monitoring the chat and I'll definitely use it a lot more in TWW ^^

and sorry for my bad english i use the google translater :D

**Comment by stevin05** [comment] 2024-08-02 13:49
Thanks for your time figuring this out. Just published the fix.

**Closed by stevin05** 2024-08-02 13:49 UTC
