### ISSUE TITLE
Craftscan vanished.

### ISSUE THREAD

**Issue by Smashnthrash** [stevin05/CraftScan#33] opened 2024-10-22 11:46 UTC
Craftscan was working great and I was making lots of money. One day it just stopped working. I cant figure out how to bring it back up. Ive tried reloading. deleting. Reinstalling. It says its a addon i have but it does not appear in game or in my crafting menu anymore. Please help.

**Comment by stevin05** [comment] 2024-10-22 20:09
It's likely hitting a lua error while loading the addon. Install BugGrabber and BugSack. These will show all lua errors and you can copy/paste it here so I can hopefully find the cause.

https://www.curseforge.com/wow/addons/bug-grabber
https://www.curseforge.com/wow/addons/bugsack


The problem is likely some unexpected data in the addon's SavedVariables.

Move this file somewhere else temporarily - it has all the configuration you've set up, so don't lose it.
`World of Warcraft\_retail_\WTF\Account\<AccountName>\SavedVariables\CraftScan.lua`

After moving it, try logging in and CraftScan will probably come up again in its default new install state. If you can easily re-create your config, you can just start fresh from there. If you copy the Lua error report here, I can probably point you to what to look for in CraftScan.lua to remove it and get your config back.

**Comment by Smashnthrash** [comment] 2024-10-23 03:10
I deleted it and reinstalled it after getting the buggrabber and bugsack. This is the errors i got:


3x CraftScan/Utils/Utils.lua:633: invalid option in `format'
[string "=[C]"]: in function `format'
[string "@CraftScan/Utils/Utils.lua"]:633: in function <CraftScan/Utils/Utils.lua:521>
[string "@CraftScan/Utils/Utils.lua"]:726: in function <CraftScan/Utils/Utils.lua:679>
[string "@CraftScan/Utils/Utils.lua"]:813: in function <CraftScan/Utils/Utils.lua:811>

Locals:
(*temporary) = "I can craft {item}. Max quality 100%. Send it on over."
(*temporary) = "{item}"

**Comment by stevin05** [comment] 2024-10-23 13:56
Replace that 100% with 100%% in CraftScan.lua and give it a try. The upgrade task that added placeholders instead of %s in the messages runs a string.format on the string and % is a special character to string.format. %% is the escape to be interpreted as a % instead of a formatter.  

I think a check was added to prevent this from being input, but will double check.

**Comment by Smashnthrash** [comment] 2024-10-23 22:42
I tried changing it in CraftScan.lua but that didnt work. Luckily I figured out I could delete saved variables or whatever in curseforge and restore it to base settings and that fixed it! Thank you for your time and attention!

**Closed** 2024-10-29 14:19 UTC
